### ISSUE TITLE
Add functionality to add / remove users

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-jenkins#5]

**Comment by tersmitten** [comment]
I don't think there's a generic way to do this. What works for us now is using the [htpasswd-auth](https://github.com/kkesha/jenkins-htpasswd-auth) plugin and add users like this:

```
  tasks:
    - name: jenkins htpasswd file
      htpasswd:
        path: /var/lib/jenkins/.htpasswd
        name: "{{ item.key }}"
        password: "{{ item.value.password }}"
      with_dict: user_credentials
      tags: always

    - name: jenkins htpasswd file(s) permissions
      file:
        path: "/var/lib/jenkins/{{ item }}"
        state: file
        owner: jenkins
        group: jenkins
        mode: 0640
      with_items:
        - .htgroups
        - .htpasswd
      tags: always
```
